FROM envoyproxy/envoy:v1.17-latest
RUN cd /tmp \
  && apt-get update \
  && apt-get install -y curl apt-utils wget\
  && rm -rf /var/lib/apt/lists/*
RUN "wget" "-O" "moesif-envoy-plugin.tar.gz" "https://github.com/Moesif/moesif-envoy-plugin/archive/0.1.7.tar.gz"
RUN "tar" "-xf" "moesif-envoy-plugin.tar.gz" "-C" "./" "--strip-components" "1"
COPY envoy.yaml /etc/envoy.yaml
COPY envoy-https.yaml /etc/envoy-https.yaml
RUN chmod go+r /etc/envoy.yaml /etc/envoy-https.yaml /moesif/core.lua
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "-l", "debug", "--service-cluster", "proxy"]